### ISSUE TITLE
process_accelerometer_data() missing 1 required positional argument: 'data' after Klipper update

### ISSUE THREAD

**Issue by rainmasak** [Frix-x/klippain-shaketune#259]
[config-20251204-002255.zip](https://github.com/user-attachments/files/23917940/config-20251204-002255.zip)

### K-Shake&Tune module branch

- [x] I confirm using the main branch

### Version

v5.2.1-0-g786abbbf

### Describe the bug and expected behavior

After updating my Klipper version to v0.13.0-416-g9c84895a0-dirty on the Raspberry I'm getting errors when running belts response macro or axes shaper calibration. 

The error appears in Klipper console while it's trying to generate the graphs.

```
...
23:34:39
Testing frequency: 134.0 Hz
23:34:41
Re-enabled [input_shaper]
23:34:48
Belts comparative frequency profile generation...
23:34:48
This may take some time (1-3min)
23:35:15
Error while generating the graphs: process_accelerometer_data() missing 1 required positional argument: 'data'
None
```

### Additional information and klippy.log

Included .stdata file for belts comparison.

Edit:
Just now noticed that there's already open issue about that: https://github.com/Frix-x/klippain-shaketune/issues/256 but I will keep this ticket open, as I have attached the .stdata file here which may be helpful.

**Comment by mdmoy55** [comment]
Temporary workaround to handle recent Klipper change in “shaper_calibrate” is to change one line in the file: 

~/shaketune/graph_creators/computations/belts_computation.py

Change:
“calibration_data = shaper_calibrate.process_accelerometer_data(data)”

To:
“calibration_data = shaper_calibrate.process_accelerometer_data(None,data)”

Restarted klipper then ran compare belts macro and it seems to work fine…

**Comment by madsi1m** [comment]
That worked for me, you might as well (temp) fix it in all 3 files:
- shaketune/graph_creators/computations/vibrations_computation.py
- shaketune/graph_creators/computations/belts_computation.py
- shaketune/graph_creators/computations/shaper_computation.py

**Comment by goandfix** [comment]
I have the same issue with AXES_SHAPER_CALIBRATION.
shaketune/graph_creators/computations/shaper_computation.py

I have to modify similar:

change:
calib_data = shaper_calibrate.process_accelerometer_data(datas)

to:
calib_data = shaper_calibrate.process_accelerometer_data(None,datas)

**Comment by mdmoy55** [comment]
Did that change work on shaper_calibration for you? It did not work for me, so for the time being I have been using existing klipper ‘shaper_calibrate’ command and plot scripts…

**Comment by madsi1m** [comment]
reboot your pi

**Comment by madsi1m** [comment]
with the input shaper I get results but there is a graph error:
```
Error while generating the graphs: x and y must have same first dimension, but have shapes (128,) and (1000,)
None
```

**Comment by mdmoy55** [comment]
For now, I’ll just wait for update to shaketune since I have belts comparison workaround and I can use klipper shaper_calibrate command and  ~/klipper/scripts/calibrate_shaper.py to handle input shaper test and make graphs…

**Comment by rainmasak** [comment]
I just downgraded Klipper on the PI for now. I'll also wait for the shaketune update.

**Comment by Frix-x** [comment]
I'm aware of this issue and will issue a fix soon

**Comment by Frix-x** [comment]
Ok, I just pushed a testing branch with a potential solution in https://github.com/Frix-x/klippain-shaketune/tree/compat-dec2025

I'll test in on my side and release the new version ASAP alongside the fix without Scipy for Trixie

**Comment by celtare21** [comment]
@Frix-x I still get
`Error while generating the graphs: x and y must have same first dimension, but have shapes (130,) and (1000,)`
On the new branch

**Comment by Frix-x** [comment]
> [@Frix-x](https://github.com/Frix-x) I still get `Error while generating the graphs: x and y must have same first dimension, but have shapes (130,) and (1000,)` On the new branch

Can you share the full Klippy log after this error please ?

**Comment by celtare21** [comment]
@Frix-x 

[klippy (16).log](https://github.com/user-attachments/files/24032625/klippy.16.log)

**Comment by celtare21** [comment]
The message doesn't seem to appear in the logs. The message from AXES_SHAPER_CALIBRATE is `// Error while generating the graphs: x and y must have same first dimension, but have shapes (130,) and (1000,)`

**Comment by celtare21** [comment]
[20251209-004823.zip](https://github.com/user-attachments/files/24042682/20251209-004823.zip)
Maybe this helps, it's the STDATA files

**Comment by Exulizer** [comment]
Hello, despite changing it, the error remains.
best regards

[klippy (1).log](https://github.com/user-attachments/files/24085269/klippy.1.log)

**Comment by DVSVIDEO** [comment]
I'm getting tired of my printer becoming unusable after updating Klipper.
This has happened to me many times... and although I've always managed to fix it, it's been unusable for several days.
I'm never updating Klipper again. (Let's not fix what isn't broken.)

**Comment by mg1975-79** [comment]
Were you able to fix the last error that’s affecting users? I’m getting the error while generating graphs now.

**Comment by MicroSur** [comment]
I dnt want to downgrade Klipper )

**Comment by ifreislich** [comment]
> I'm getting tired of my printer becoming unusable after updating Klipper. This has happened to me many times... and although I've always managed to fix it, it's been unusable for several days. I'm never updating Klipper again. (Let's not fix what isn't broken.)

Klipper is just fine. 3rd party stuff isn't keeping up with the changes to klipper.

**Comment by 3DeezNutz** [comment]
> I'm aware of this issue and will issue a fix soon

How do i install this fix?

**Comment by ifreislich** [comment]
> How do i install this fix?

I pinged you on the klipper discord.

**Comment by celtare21** [comment]
The fix is not working yet

**Comment by b00gie-dev** [comment]
For me unfortunately neither.

**Comment by renekar** [comment]
when can we except a fix?

**Comment by HairyStuntWaffle** [comment]
> when can we except a fix?

Guessing christmas got in the way, give the poor guy a few days! 
Having said that, pushing fix would be cool, any way I can assist in testing just let me know.

**Comment by Cowbite** [comment]
Still no fix? I think it's time to go back to stock shaper graphs as this is getting out of hand too often.

**Comment by Cowbite** [comment]
> > when can we except a fix?
> 
> Guessing christmas got in the way, give the poor guy a few days! Having said that, pushing fix would be cool, any way I can assist in testing just let me know.

I would usually totally agree with you. Things break. This issue is over 3 weeks old, however.

**Comment by Cowbite** [comment]
Bug still present in most recent Klipper update:
v0.13.0-448-g51dcb09d

**Comment by ErlingK1** [comment]
I rolled klipper back to  v0.13.0-403 and it works fine again. Looks like these commits to klipper made the change. Hope it helps with the troubleshooting.

<img width="1290" height="258" alt="Image" src="https://github.com/user-attachments/assets/b0222525-2f9b-41b7-a255-0ea799cce42b" />

What I did:
- Optional back up your config
cp -a ~/printer_data/config ~/printer_data/config.backup_$(date +%F)

- Stop services
sudo systemctl stop klipper moonraker || true

- Go to the Klipper repo and fetch latest refs/tags
cd ~/klipper
git fetch --all --tags --prune

- If you have local changes, stash them
git stash push -u -m "before rollback to v0.13.0-403" || true

- Checkout the exact v0.13.0-403 commit
git checkout b4c7cf4a3

- Verify you’re on the expected revision
git describe --tags --dirty
   expected something like: v0.13.0-403-gb4c7cf4a3

- Start services again
sudo systemctl start moonraker klipper

**Comment by cha0stype** [comment]
I installed the fix from the branch today and for me it seems to work just fine.
I ran `COMPARE_BELTS_RESPONSES` (x2),` AXES_SHAPER_CALIBRATION` (x2) and `CREATE_VIBRATIONS_PROFILE` without getting an error.

It generated the graphs just fine as well.
NOTE: I'm running Kalico instead of Klipper

**Comment by Cowbite** [comment]
> I installed the fix from the branch today and for me it seems to work just fine. I ran `COMPARE_BELTS_RESPONSES` (x2),` AXES_SHAPER_CALIBRATION` (x2) and `CREATE_VIBRATIONS_PROFILE` without getting an error.
> 
> It generated the graphs just fine as well. NOTE: I'm running Kalico instead of Klipper

 Which fix?

**Comment by celtare21** [comment]
> I installed the fix from the branch today and for me it seems to work just fine. I ran `COMPARE_BELTS_RESPONSES` (x2),` AXES_SHAPER_CALIBRATION` (x2) and `CREATE_VIBRATIONS_PROFILE` without getting an error.
> 
> It generated the graphs just fine as well. NOTE: I'm running Kalico instead of Klipper

Kalico doesn't really keep up with mainline Klipper. That doesn't mean the fix is working, that only means that kalico doesn't have the offending commits breaking klippain

**Comment by cha0stype** [comment]
> > I installed the fix from the branch today and for me it seems to work just fine. I ran `COMPARE_BELTS_RESPONSES` (x2),` AXES_SHAPER_CALIBRATION` (x2) and `CREATE_VIBRATIONS_PROFILE` without getting an error.
> > It generated the graphs just fine as well. NOTE: I'm running Kalico instead of Klipper
> 
> Which fix?

This one: 

> Ok, I just pushed a testing branch with a potential solution in https://github.com/Frix-x/klippain-shaketune/tree/compat-dec2025
> 
> I'll test in on my side and release the new version ASAP alongside the fix without Scipy for Trixie

> Kalico doesn't really keep up with mainline Klipper. That doesn't mean the fix is working, that only means that kalico doesn't have > the offending commits breaking klippain
Yes I know. I didn't think about it until after I commented, thus my edit. 

I also peeked into the posted log, but there isn't any error messages in them, so I wasn't able to investigate any further.

**Comment by Frix-x** [comment]
This is indeed a known error that I already partially fixed but it was not enough for Klipper users. So I just pushed a final update on the compat-dec2025 branch. So if you are already on this branch, just pull the latest commits and let me know if it's correctly working now!

**Comment by celtare21** [comment]
> This is indeed a known error that I already partially fixed but it was not enough for Klipper users. So I just pushed a final update on the compat-dec2025 branch. So if you are already on this branch, just pull the latest commits and let me know if it's correctly working now!

I'll test tomorrow when I wake up

**Comment by llluis** [comment]
> let me know if it's correctly working now!

Using Shake&Tune version: v5.2.1-15-gb012e5e
All good with AXES_SHAPER_CALIBRATION and klipper v0.13.0-454-ge60fe3d9

**Comment by mdmoy55** [comment]
Input Shaper test/graphs now work fine with latest Klipper release on an 
OrangePi running Trixie with latest updates. Thank you for your 
continued efforts and support for a most-valued klipper add-in!

Best,



------ Original Message ------
From "Félix Boisselier" ***@***.***>
To "Frix-x/klippain-shaketune" ***@***.***>
Cc "mdmoy55" ***@***.***>; "Comment" ***@***.***>
Date 1/4/2026 2:36:27 PM
Subject Re: [Frix-x/klippain-shaketune] process_accelerometer_data() 
missing 1 required positional argument: 'data' after Klipper update 
(Issue #259)

**Comment by Frix-x** [comment]
Super! I'll polish the code a bit and will merge it soon

**Comment by Frix-x** [comment]
Merged in develop now

**Comment by mdmoy55** [comment]
For my own education, was issue related to calls to matplotlib? I was 
trying to learn by looking at how the various pieces of shaketune called 
each other, and got as far as the computations and graph creators, but 
my aging brain (brought up on COBOL in the 1970s…) could not get any 
further….

Anyway, thanks again!




------ Original Message ------
From "Félix Boisselier" ***@***.***>
To "Frix-x/klippain-shaketune" ***@***.***>
Cc "mdmoy55" ***@***.***>; "Comment" ***@***.***>
Date 1/5/2026 1:12:35 AM
Subject Re: [Frix-x/klippain-shaketune] process_accelerometer_data() 
missing 1 required positional argument: 'data' after Klipper update 
(Issue #259)

**Comment by Cowbite** [comment]
> v5.2.1-15-gb012e5e

Sorry but how to I switch to v5.2.1-15-gb012e5e.? I'm pretty green when it comes to
 github.

**Comment by cha0stype** [comment]
> > v5.2.1-15-gb012e5e
> 
> Sorry but how to I switch to v5.2.1-15-gb012e5e.? I'm pretty green when it comes to github.

The fix is currently in the development branch.

```bash
cd ~
rm -r klippain_shaketune
git clone https://github.com/Frix-x/klippain-shaketune/ -b develop
mv klippain-shaketune klippain_shaketune
./klippain_shaketune/install.sh```

**Comment by cha0stype** [comment]
> For my own education, was issue related to calls to matplotlib? I was
> trying to learn by looking at how the various pieces of shaketune called
> each other, and got as far as the computations and graph creators, but
> my aging brain (brought up on COBOL in the 1970s…) could not get any
> further….
> 
> Anyway, thanks again!
> […](#)

@mdmoy55 Matplotlib was what raised the error, as it was given data with mismatching X and Y dimensions. This was caused by klipper deciding to interpolate shaper values and thus increasing size of the Y array given to matplotlib.

(It's bit of a tl;dr but I hope it summarize the issue well enough)

**Comment by wirewound** [comment]
Switching to develop branch and running the install.sh script geneates folowing error:

>ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. scipy 1.11.4 requires numpy<1.28.0,>=1.21.6, but you have numpy 2.2.2 which is incompatible.

This results in a Klipper startup error:

> Internal error during connect: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Switching back to main solves the Klipper error but the initial problem remains.

Version: v0.13.0-454-ge60fe3d99-dirty
OS: Debian GNU/Linux 12 (bookworm)
Distro: MainsailOS 2.2.2 (bookworm)

**Comment by wkeifenheim** [comment]
I just activated the klipper python environment and upgraded `scipy`, that worked.

```bash
source ~/klippy-env/bin/activate
pip install --upgrade scipy
```
Which then installed `scipy` v1.13.1 and got me rolling again with shaketune.

**Comment by renekar** [comment]
It's closed but only available as developer branch? When will it be officially released?
